version: '3.8'

services:
  app:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    command: [ "python", "bot.py" ]
    depends_on:
      - db
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}

volumes:
  postgres_data: